### ISSUE TITLE
请问要怎么运行？

### ISSUE THREAD

**Issue by ChanaLii** [xjoker/AppleMonitor#2]
我对C语言不是很熟，找不到程序运行入口，使用的编辑器是Clion。

**Comment by xjoker** [comment]
这个是 .Net (c#) 语言
其实你只要用自己熟悉的语言请求
https://www.apple.com.cn/shop/pickup-message-recommendations?mt=compact&location=福建 福州 晋安区&product=MLT93CH/A

将参数内的 location 和 product 替换，请求后看 PartsAvailability 是否有数据即可😄

**Comment by ChanaLii** [comment]
了解！
![image](https://user-images.githubusercontent.com/20842481/136739066-7d77973f-5a41-4520-99d3-4cdbb1557763.png)

我大概看了下源码，其逻辑是检测到有库存的时候给飞书发一个通知让用户迅速下单是吧？

**Comment by xjoker** [comment]
是的
结果可能存在多个 Apple Store，需要自己过滤一下😄
